### ISSUE TITLE
fontname and fontsize are not displayed.

### ISSUE THREAD

**Issue by armelsoubeiga** [LukasK13/SummeRnote#1]
I use your package in my shiny app. But the font names and sizes are not displayed. Check instead icon.

`
toolbar = list(
                    list("style", c("bold", "italic", "underline")),
                    list("font", c("superscript", "subscript")),
                    list("fontname", c("fontname")),
                    list("fontsize", c("fontsize")),
                    list("Misc", c("codeview")))
`

![image](https://user-images.githubusercontent.com/38792575/152504831-6b6d268f-5590-45fe-bb2b-69ff7d8649a8.png)

**Comment by LukasK13** [comment]
I'm very sorry, but I'm no longer using R and therefore cannot help you. My advice is to update the summernote JS library to see, if there are any incompatibilities.

**Comment by armelsoubeiga** [comment]
Thank you for your answer. I solved the problem. It is the summernote CSS that is not  incompatible.

**Comment by bengaff** [comment]
> Thank you for your answer. I solved the problem. It is the summernote CSS that is not incompatible.

Hi @armelsoubeiga - Could you let us know what you changed in the summernote CSS to fix this? Thank you!
